---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/13/24 12:15 AM
---

require 'Core/__lib'
require 'Core/__external'
require 'Core/LuaBehaviour'
require 'Core/Object'
require 'Core/GameObject'

ComponentA = LuaBehaviour:new()
function ComponentA:Start()  end
function ComponentA:Update()  end

ComponentB = LuaBehaviour:new()
function ComponentB:Start()  end
function ComponentB:Update()  end

ComponentC = LuaBehaviour:new()
function ComponentC:Start()  end
function ComponentC:Update()  end

local go1 = GameObject:new(-1, 'Some entity')

__all_components['0 :: Scripts/ComponentA'] = ComponentA:new()
__all_components['0 :: Scripts/ComponentA'].__type_name = 'ComponentA'
__all_components['0 :: Scripts/ComponentA'].__type_filepath = 'Scripts/ComponentA'
__all_components['0 :: Scripts/ComponentA'].gameObject = go1
__all_components['0 :: Scripts/ComponentA'].transform = go1.transform

local go2 = GameObject:new(-1, 'Some entity')

__all_components['1 :: Scripts/ComponentA'] = ComponentA:new()
__all_components['1 :: Scripts/ComponentA'].__type_name = 'ComponentA'
__all_components['1 :: Scripts/ComponentA'].__type_filepath = 'Scripts/ComponentA'
__all_components['1 :: Scripts/ComponentA'].gameObject = go2
__all_components['1 :: Scripts/ComponentA'].transform = go2.transform

__all_components['1 :: Scripts/ComponentB'] = ComponentB:new()
__all_components['1 :: Scripts/ComponentB'].__type_name = 'ComponentB'
__all_components['1 :: Scripts/ComponentB'].__type_filepath = 'Scripts/ComponentB'
__all_components['1 :: Scripts/ComponentB'].gameObject = go2
__all_components['1 :: Scripts/ComponentB'].transform = go2.transform

local go3 = GameObject:new(-1, 'Some entity')

__all_components['2 :: Scripts/ComponentB'] = ComponentC:new()
__all_components['2 :: Scripts/ComponentB'].__type_name = 'ComponentC'
__all_components['2 :: Scripts/ComponentB'].__type_filepath = 'Scripts/ComponentC'
__all_components['2 :: Scripts/ComponentB'].gameObject = go3
__all_components['2 :: Scripts/ComponentB'].transform = go3.transform

print(table_length(Object.FindObjectsOfType(ComponentA)))
print(table_length(Object.FindObjectsOfType(ComponentB)))
print(table_length(Object.FindObjectsOfType(ComponentC)))
