---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/13/24 12:15 AM
---

require 'Core/__lib'
require 'Core/__external'
require 'Core/LuaBehaviour'
require 'Core/Object'
require 'Core/GameObject'

-- ensure that scene empty
print(table_length(__all_game_objects))
print(table_length(__all_components))

BotController = LuaBehaviour:new()
BotController.motionSpeed = 1.0
function BotController:Start()  end
function BotController:Update()
  self.transform:Translate(Vector3.forward * self.motionSpeed);
end

EnemyController = LuaBehaviour:new()
function EnemyController:Start()  end
function EnemyController:Update()  end

local orig = GameObject:new(-1, 'Some entity')
orig.transform.position:Set(10.0, 20.0, 30.0)
orig.__components['BotController'] = BotController
orig.__components['BotController'].__type_name = 'BotController'
orig.__components['BotController'].__type_filepath = 'Scripts/BotController'
orig.__components['EnemyController'] = EnemyController
orig.__components['EnemyController'].__type_name = 'EnemyController'
orig.__components['EnemyController'].__type_filepath = 'Scripts/EnemyController'

local clone1 = Object.Instantiate(orig)
print(clone1.name)
print(table_length(__all_game_objects))
print(table_length(__all_components))
print(table_length(__all_components[clone1.__instanceID]))
print(__all_components[clone1.__instanceID]['BotController'].__type_filepath)
print(__all_components[clone1.__instanceID]['EnemyController'].__type_filepath)

local clone2 = Object.Instantiate(orig)
print(clone2.name)
print(table_length(__all_game_objects))
print(table_length(__all_components))
print(table_length(__all_components[clone2.__instanceID]))
print(__all_components[clone2.__instanceID]['BotController'].__type_filepath)
print(__all_components[clone2.__instanceID]['EnemyController'].__type_filepath)

-- ensure components were registered
print(__all_components[0]['BotController'].motionSpeed)
print(__all_components[1]['BotController'].motionSpeed)

-- makes bot 2 faster
__all_components[1]['BotController'].motionSpeed = 2.0

-- check Update works fine
print(__all_game_objects[0].transform.position:ToString())
print(__all_game_objects[1].transform.position:ToString())
__all_components[0]['BotController']:Update()
__all_components[0]['BotController']:Update()
__all_components[1]['BotController']:Update()
__all_components[1]['BotController']:Update()
print(__all_game_objects[0].transform.position:ToString())
print(__all_game_objects[1].transform.position:ToString())
