---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 12/29/23 2:44 PM
---

require "Core/LuaBehaviour"

DroneController = LuaBehaviour:new()

DroneController.motionSpeed = 0.0
DroneController.targetTr = Transform
DroneController.maxDistance = 75.0

function DroneController:Start()
    Debug.Log("DroneController :: Start");

    if (self.motionSpeed == 0.0) then
        Debug.LogWarning("motionSpeed should not be equals zero")
    end
    if (self.targetTr == nil) then
        Debug.LogError("targetTr is required")
    else
        Debug.Log("targetTr = " .. self.targetTr.position:ToString())
    end
end

function DroneController:Update()
    Debug.Log("DroneController :: Update");

    if self.targetTr == nil then
        return
    end

    self.transform:LookAt(self.targetTr);
    self.transform:Translate(Vector3.right * self.motionSpeed * Time.deltaTime);

    local distance = self.transform.position:Distance(self.targetTr.position);
    Debug.Log("Distance to target " .. distance);
    if distance > self.maxDistance then
        local movement = distance - self.maxDistance
        self.transform:LookAt(self.targetTr);
        self.transform:Translate(Vector3.forward * movement * Time.deltaTime);
    end
end
