---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 12/29/23 2:44 PM
---

require "Core/LuaBehaviour"
require "Core/Time"

SpinnerController = LuaBehaviour:new()

SpinnerController.rotationSpeed = 0.0

function SpinnerController:Start()
    Debug.Log("SpinnerController :: Start");

    if (self.rotationSpeed == 0.0) then
        Debug.LogWarning("rotationSpeed should not be equals zero")
    end
end

function SpinnerController:Update()
    --Debug.Log("SpinnerController :: Update");

    self.transform:Rotate(Vector3:new(
            0.0,
            0.0,
            self.rotationSpeed * Time.deltaTime
    ))
    --Debug.Log("Angle Y for " .. self.gameObject.name .. " is " .. self.transform.rotation.eulerAngles.z);
end
