---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/10/24 4:29 PM
---

require "Core/LuaBehaviour"

ProjectileController = {}

--ProjectileController.ttlInFrames = 10
--ProjectileController.framesCount = 0
--ProjectileController.motionSpeed = 20.0

function ProjectileController:Awake()
    self.ttlInFrames = self.ttlInFrames or 10
    self.framesCount = self.framesCount or 0
    self.motionSpeed = self.motionSpeed or 20.0

    Debug.Log("ProjectileController:Awake")
end

function ProjectileController:Start()
    --
end

function ProjectileController:Update()
    if self.framesCount >= self.ttlInFrames then
        Object.Destroy(self.gameObject)
        Debug.Log("Remove projectile because frame count is " .. self.framesCount)
        return
    end
    self.framesCount = self.framesCount + 1

    local movement = self.transform.rotation
            * Vector3.forward
            * self.motionSpeed
            * Time.deltaTime;
    self.transform:Translate(movement)
end
