---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/13/24 9:53 PM
---

require 'Core'

DroneController = LuaBehaviour:new()

function DroneController:Awake()
    self.motionSpeed = self.motionSpeed or 0.0
    self.targetTr = self.targetTr or Transform
end

function DroneController:Start()
    Debug.Log("DroneController :: Start");
end

function DroneController:Update()
    Debug.Log("DroneController :: Update");

    local move = Vector3.right * self.motionSpeed * Time.deltaTime
    print('  next move ' .. move.x .. ' ' .. move.y .. ' ' .. move.z)
    self.transform:Translate(move);
end
