---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 12/29/23 2:44 PM
---

require "Core/LuaBehaviour"

BaseBanner = {}

BaseBanner.isDestroyed = false

function BaseBanner:Start()
    -- TODO: ???
end

function BaseBanner:Update()
    if self.isDestroyed == true then
        Debug.Log("GAME OVER: base destroyed");
        Application.Quit();
    end
end
