---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/21/24 5:00 PM
---

require "Core/LuaBehaviour"
require "Core/Object"

EnemyRespawnPoint = LuaBehaviour:new()

EnemyRespawnPoint.request = ""
EnemyRespawnPoint.tank1Prefab = GameObject:new(-1, "")

function EnemyRespawnPoint:Start()
    Debug.Log("Enemy respawn point '" .. self.gameObject.name .. "' are ready...")
end

function EnemyRespawnPoint:Update()
    if self.request == "tank1" then
        Object.Instantiate(
                self.tank1Prefab,
                self.transform.position,
                Quaternion.identity
        );
    end

    -- TODO: create new enemy instance
end
