---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/21/24 5:00 PM
---

require "Core/LuaBehaviour"

EnemyRespawnSystem = LuaBehaviour:new()

function EnemyRespawnSystem:Start()
    -- TODO: collect all respawn points
end

function EnemyRespawnSystem:Update()
    -- TODO: request new enemy
end
