---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/21/24 5:26 PM
---

require "Core/LuaBehaviour"

EnemyController = LuaBehaviour:new()

function EnemyController:Start()
    --
end

function EnemyController:Update()
    -- TODO: move to base
    -- TODO: shot forward
    -- TODO: avoid obstacles
end