---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/21/24 5:00 PM
---

require "Core/LuaBehaviour"
require "Core/Object"

EnemyRespawnPoint = LuaBehaviour:new()

function EnemyRespawnPoint:Awake()
    self.request = self.request or ""
    self.tank1Prefab = self.tank1Prefab or nil
end

function EnemyRespawnPoint:Start()
    if self.tank1Prefab == nil then
        Debug.LogWarning("Need to specify prefab for Tank 1")
    end
end

function EnemyRespawnPoint:Update()
    if self.request == "tank1" then
        if self.tank1Prefab == nil then
            Debug.LogError("Need to specify prefab for Tank 1")
        end
        Object.Instantiate(
                self.tank1Prefab,
                self.transform.position,
                Quaternion.Euler(0.0, 180.0, 0.0)
        );
        self.request = ""
    end

    -- TODO: create new enemy instance
end
