---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/13/24 12:49 PM
---

require "Core/LuaBehaviour"

FriendController = LuaBehaviour:new()

function FriendController:Start()
    --
end

function FriendController:Update()
    -- TODO: protect base banner
    -- TODO: shot forward
    -- TODO: avoid obstacles
end
