---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/13/24 12:51 PM
---

require "Core/LuaBehaviour"
require "Core/Object"

HittingSystem = LuaBehaviour:new()

function HittingSystem:Start()
    --
end

function HittingSystem:Update()
    local shells = Object.FindObjectsOfType(ProjectileController)
    if table_length(shells) == 0 then
        -- no shells/bullets on scene, so skip
        return
    end

    -- TODO: check hitting with base banner (game over)

    local obstacles = Object.FindObjectsOfType(Obstacle)
    for _, shellCmp in pairs(shells) do
        for _, obsCmp in pairs(obstacles) do
            if Vector3.Distance(shellCmp.transform.position, obsCmp.transform.position) < 8.0 then
                obsCmp.solidity = obsCmp.solidity - 1
                if obsCmp.solidity <= 0 then
                    Object.Destroy(obsCmp.gameObject)
                end
                Object.Destroy(shellCmp.gameObject)
            end
        end
    end

    -- TODO: check hitting tank from another team

end
