---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/13/24 12:57 PM
---

require "Core/Collision"

Obstacle = LuaBehaviour:new()

Obstacle.solidity = 0

function Obstacle:Start()
    --
end

function Obstacle:Update()
    --
end

function Obstacle:OnCollisionEnter(collision --[[Collision]])
    Debug.Log("GO " .. self.gameObject.name " detect hit with " .. collision.gameObject.name)
end
