---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/13/24 12:57 PM
---

require "Core/Collision"

Obstacle = LuaBehaviour:new()

function Obstacle:Awake()
    self.solidity = 0
end

function Obstacle:Start()
    --
end

function Obstacle:Update()
    --
end

--function Obstacle:OnCollisionEnter(collision --[[Collision]])
--    if collision.gameObject:GetComponent(Obstacle) ~= nil then
--        return
--    end
--    if collision.gameObject:GetComponent(BaseBanner) ~= nil then
--        return
--    end
--
--    Debug.Log("GO " .. self.gameObject.name .. " detect hit with " .. collision.gameObject.name)
--end
