---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/13/24 12:57 PM
---

Obstacle = LuaBehaviour:new()

Obstacle.solidity = 0

function Obstacle:Start()
    --
end

function Obstacle:Update()
    --
end
