---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/10/24 4:29 PM
---

require "Core/LuaBehaviour"

ProjectileController = LuaBehaviour:new()

ProjectileController.motionSpeed = 20.0

function ProjectileController:Start()
    --
end

function ProjectileController:Update()
    --if self.transform.position.x < -70
    --        or self.transform.position.x > 70
    --        or self.transform.position.z < -70
    --        or self.transform.position.z > 70 then
    --    Object.Destroy(self.gameObject);
    --    Debug.Log("Remove projectile");
    --    return ;
    --end

    local movement = self.transform.rotation
            * Vector3.forward
            * self.motionSpeed
            * Time.deltaTime;
    self.transform:Translate(movement)
end
