---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/10/24 4:29 PM
---

require "Core/LuaBehaviour"

ProjectileController = {}

ProjectileController.motionSpeed = 20.0
ProjectileController.senderObject = nil

function ProjectileController:Start()
    --
end

function ProjectileController:Update()
    if self.transform.position.x < -70
            or self.transform.position.x > 70
            or self.transform.position.z < -70
            or self.transform.position.z > 70 then
        Object.Destroy(self.gameObject)
        Debug.Log("Remove projectile")
        return
    end

    local movement = Vector3.forward
            * self.motionSpeed
            * Time.deltaTime;
    self.transform:Translate(movement)
end
