---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/13/24 12:57 PM
---

Tank = LuaBehaviour:new()

function Tank:Start()
    self.solidity = self.solidity or 1
end

function Tank:Start()
    --
end

function Tank:Update()
    --
end
