---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/13/24 4:54 AM
---

require "Core/KeyCode"

__all_game_objects = {}
__all_components = {}

__global_buttons_pressed = {
    [KeyCode.W] = false,
    [KeyCode.A] = false,
    [KeyCode.S] = false,
    [KeyCode.D] = false,

    [KeyCode.UpArrow] = false,
    [KeyCode.DownArrow] = false,
    [KeyCode.RightArrow] = false,
    [KeyCode.LeftArrow] = false,

    [KeyCode.Escape] = false,
    [KeyCode.Ctrl] = false,
    [KeyCode.Space] = false,

    [KeyCode.Mouse0] = false,
    [KeyCode.Mouse1] = false,
    [KeyCode.Mouse2] = false,
}
__global_buttons_hold = {}
__global_buttons_released = {
    [KeyCode.W] = false,
    [KeyCode.A] = false,
    [KeyCode.S] = false,
    [KeyCode.D] = false,

    [KeyCode.UpArrow] = false,
    [KeyCode.DownArrow] = false,
    [KeyCode.RightArrow] = false,
    [KeyCode.LeftArrow] = false,

    [KeyCode.Escape] = false,
    [KeyCode.Ctrl] = false,
    [KeyCode.Space] = false,

    [KeyCode.Mouse0] = false,
    [KeyCode.Mouse1] = false,
    [KeyCode.Mouse2] = false,
}

function __before_update_frame()
    for keyCode, keyState in pairs(__global_buttons_pressed) do
        if keyState == true then
            if __global_buttons_hold[keyCode] == true then
                __global_buttons_pressed[keyCode] = false
            else
                __global_buttons_hold[keyCode] = true
            end
        end
    end

    for keyCode, keyState in pairs(__global_buttons_released) do
        if keyState == true then
            __global_buttons_hold[keyCode] = false
        end
    end
end

function __on_update_frame()
    for _, cmpInstance in pairs(__all_components) do
        if (cmpInstance.enabled) then
            cmpInstance:Update()
        end
    end
end

function __after_update_frame()
    for keyCode, _ in pairs(__global_buttons_pressed) do
        __global_buttons_pressed[keyCode] = false
    end

    for keyCode, _ in pairs(__global_buttons_released) do
        __global_buttons_released[keyCode] = false
    end
end
