---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/13/24 4:54 AM
---

require "Core/KeyCode"
require "Core/Time"

__time_delta = 0.0

__scene_next_game_object_instance_id = nil

--- Table with all game objects, placed on scene.
--- Key is instance ID.
--- Value is table that inherited from GameObject.
__all_game_objects = {}
__all_components = {}

__global_buttons_pressed = {
    [KeyCode.W] = false,
    [KeyCode.A] = false,
    [KeyCode.S] = false,
    [KeyCode.D] = false,

    [KeyCode.UpArrow] = false,
    [KeyCode.DownArrow] = false,
    [KeyCode.RightArrow] = false,
    [KeyCode.LeftArrow] = false,

    [KeyCode.Escape] = false,
    [KeyCode.Ctrl] = false,
    [KeyCode.Space] = false,

    [KeyCode.Mouse0] = false,
    [KeyCode.Mouse1] = false,
    [KeyCode.Mouse2] = false,
}
__global_buttons_hold = {}
__global_buttons_released = {
    [KeyCode.W] = false,
    [KeyCode.A] = false,
    [KeyCode.S] = false,
    [KeyCode.D] = false,

    [KeyCode.UpArrow] = false,
    [KeyCode.DownArrow] = false,
    [KeyCode.RightArrow] = false,
    [KeyCode.LeftArrow] = false,

    [KeyCode.Escape] = false,
    [KeyCode.Ctrl] = false,
    [KeyCode.Space] = false,

    [KeyCode.Mouse0] = false,
    [KeyCode.Mouse1] = false,
    [KeyCode.Mouse2] = false,
}

-- TODO: load from ${PROJECT_DIR}/input-mapping.json
__input_mapping = {
    axes = {
        ["Vertical"] = {
            ["positive"] = { [0] = KeyCode.W, [1] = KeyCode.UpArrow },
            ["negative"] = { [0] = KeyCode.S, [1] = KeyCode.DownArrow },
        },
        ["Horizontal"] = {
            ["positive"] = { [0] = KeyCode.D, [1] = KeyCode.RightArrow },
            ["negative"] = { [0] = KeyCode.A, [1] = KeyCode.LeftArrow },
        },
    },
    buttons = {
        ["Fire1"] = {
            ["triggers"] = { [0] = KeyCode.Mouse0 }
        },
    }
}

__application_quit = false

__global_prefab_game_objects = {}
