---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/22/24 5:30 AM
---

function table_length(T)
  local count = 0
  for _ in pairs(T) do count = count + 1 end
  return count
end