---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/20/24 10:52 AM
---

require "Core/Vector3"

PhysicsSystem = {}

function PhysicsSystem.hasCollision(collider1 --[[BoxCollider]], collider2 --[[BoxCollider]])

end

function PhysicsSystem.getBoxColliderVertices(collider --[[BoxCollider]])

end

function PhysicsSystem.isPointInsideBoxCollider(point --[[Vector3]], collider --[[BoxCollider]])
    -- https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_collision_detection#point_vs._aabb

    local boxPos = collider.transform.position + collider.center

    local minX = boxPos.x - collider.size.x / 2.0
    local maxX = boxPos.x + collider.size.x / 2.0

    local minY = boxPos.y - collider.size.y / 2.0
    local maxY = boxPos.y + collider.size.y / 2.0

    local minZ = boxPos.z - collider.size.z / 2.0
    local maxZ = boxPos.z + collider.size.z / 2.0

    return point.x >= minX and point.x <= maxX
            and point.y >= minY and point.y <= maxY
            and point.z >= minZ and point.z <= maxZ
end