---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/20/24 1:41 PM
---

require "Core/__external"

Application = {}

--- https://docs.unity3d.com/ScriptReference/Application.Quit.html
Application.Quit = function()
    __application_quit = true
end
