---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/19/24 11:17 PM
---

Collision = {}

function Collision:new(gameObject --[[GameObject]])
    local c = {
        gameObject = gameObject,
    }

    self.__index = self
    setmetatable(c, self)

    return c
end