---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/19/24 11:17 PM
---

Collision = {}

function Collision:new(gameObject --[[GameObject]])
    if not gameObject:IsA("GameObject") then
        Debug.LogError("Wrong gameObject type for collision")
        return nil
    end

    local c = {
        gameObject = gameObject,
        transform = gameObject.transform,
    }

    self.__index = self
    setmetatable(c, self)

    return c
end