---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/5/24 11:20 AM
---

Color = {
    r = 0.0,
    g = 0.0,
    b = 0.0,
    a = 0.0,
}

function Color:new(red --[[number]], green --[[number]], blue --[[number]], alpha --[[number]])
    red = red or 1.0
    green = green or 1.0
    blue = blue or 1.0
    alpha = alpha or 1.0

    clr = {
        r = red,
        g = green,
        b = blue,
        a = alpha,
    }

    self.__index = self
    setmetatable(clr, self)

    return clr
end