---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 12/29/23 8:39 PM
---

Debug = {}

function Debug.Log(message --[[string]])
    print('DEBUG: ' .. message)
end

function Debug.LogWarning(message --[[string]])
    print('WARN:  ' .. message)
end

function Debug.LogError(message --[[string]])
    print('ERROR: ' .. message)
end
