---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 12/31/23 11:10 AM
---

require 'Core/Object'
require 'Core/Transform'

GameObject = Object:new(0)
GameObject = {
    id = "",
    name = "",
    transform = Transform:new(),
}

function GameObject:new(id --[[string]], name --[[string]])
    id = id or ""
    name = name or ""

    gameObj = {
        id = id,
        name = name,
        transform = Transform:new(),
    }

    self.__index = self
    setmetatable(gameObj, self)

    return gameObj
end

function GameObject:IsA(className --[[string]])
    return className == "GameObject"
end

function GameObject:AddComponent(name --[[string]])
    -- TODO: implement me
    return nil
end

function GameObject.Find(name --[[string]])
    -- TODO: implement me
    return nil
end
