---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 12/31/23 11:10 AM
---

require 'Core/Transform'

GameObject = {
    name = "",
    components = {},
    transform = Transform:new(),
}

function GameObject:new(name --[[string]], components)
    name = name or ""
    components = components or {}

    go = {
        name = name,
        components = components,
        transform = Transform:new(),
    }
    self.__index = self
    setmetatable(go, self)

    return go
end

function GameObject.Find(name --[[string]])
    -- TODO: implement me
    return nil
end
