---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 12/30/23 10:29 AM
---

require "Core/__lib"
require "Core/__external"
require "Core/__runtime"

require "Core/Debug"
require "Core/Time"
require "Core/Space"

require "Core/Color"
require "Core/Vector3"
require "Core/Quaternion"
require "Core/Transform"
require "Core/GameObject"

require "Core/LuaBehaviour"

require "Core/KeyCode"
require "Core/Input"
