---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/13/24 3:34 AM
---

require "Core/KeyCode"

Input = {}

--- https://docs.unity3d.com/ScriptReference/Input.GetButtonDown.html
--- Returns true during the frame the user pressed down the virtual button identified by buttonName.
Input.GetButtonDown = function(buttonName --[[string]])
    if axisName == "Fire1" then
        return __global_buttons_pressed[KeyCode.Mouse0] ~= nil
    end

    Debug.LogError("GetButtonDown: unexpected button name: " .. buttonName)

    return false
end

--- https://docs.unity3d.com/ScriptReference/Input.GetButtonUp.html
--- Returns true the first frame the user releases the virtual button identified by buttonName.
Input.GetButtonUp = function(buttonName --[[string]])
    if axisName == "Fire1" then
        return __global_buttons_released[KeyCode.Mouse0] ~= nil
    end

    Debug.LogError("GetButtonUp: unexpected button name: " .. buttonName)

    return false
end

--- https://docs.unity3d.com/ScriptReference/Input.GetButton.html
--- bool True when an axis has been pressed and not released.
Input.GetButton = function(buttonName --[[string]])
    if axisName == "Fire1" then
        return __global_buttons_hold[KeyCode.Mouse0] ~= nil
    end

    Debug.LogError("GetButton: unexpected button name: " .. buttonName)

    return false
end

--- https://docs.unity3d.com/ScriptReference/Input.GetAxis.html
--- Returns the value of the virtual axis identified by axisName.
Input.GetAxis = function(axisName --[[string]])
    if axisName == "Vertical" then
        if __global_buttons_hold[KeyCode.W] == true and __global_buttons_hold[KeyCode.S] == true then
            -- press both
            return 0.0
        end

        if __global_buttons_hold[KeyCode.W] == true then
            return 1.0
        end
        if __global_buttons_hold[KeyCode.S] == true then
            return -1.0
        end

        return 0.0
    end
    if axisName == "Horizontal" then
        if __global_buttons_hold[KeyCode.D] == true and __global_buttons_hold[KeyCode.A] == true then
            -- press both
            return 0.0
        end

        if __global_buttons_hold[KeyCode.D] == true then
            return 1.0
        end
        if __global_buttons_hold[KeyCode.A] == true then
            return -1.0
        end

        return 0.0
    end

    Debug.LogError("GetAxis: unexpected axis name: " .. axisName)

    return 0.0
end
