---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/13/24 3:43 AM
---

KeyCode = {}

KeyCode.W = "w";
KeyCode.A = "a";
KeyCode.S = "s";
KeyCode.D = "d";

KeyCode.UpArrow = "arrow-up";
KeyCode.DownArrow = "arrow-down";
KeyCode.RightArrow = "arrow-right";
KeyCode.LeftArrow = "arrow-left";

KeyCode.Escape = "ESC";
KeyCode.Ctrl = "CTRL";
KeyCode.Space = "SPACE";

KeyCode.Mouse0 = "MSL"; -- The Left (or primary) mouse button.
KeyCode.Mouse1 = "MSR"; -- Right mouse button (or secondary mouse button).
KeyCode.Mouse2 = "MSM"; -- Middle mouse button (or third button).
