---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/13/24 3:43 AM
---

KeyCode = {}

KeyCode.W = 119; -- 87 119
KeyCode.A = 97; -- 65  97
KeyCode.S = 115; -- 83 115
KeyCode.D = 100; -- 68 100

KeyCode.Escape = 27;
KeyCode.Ctrl = 17;
KeyCode.Alt = "<alt>";
KeyCode.Space = 32;

KeyCode.Mouse0 = "MSL"; -- The Left (or primary) mouse button.
KeyCode.Mouse1 = "MSR"; -- Right mouse button (or secondary mouse button).
KeyCode.Mouse2 = "MSM"; -- Middle mouse button (or third button).
