---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/1/24 3:42 PM
---

Quaternion = { w = 0.0, x = 0.0, y = 0.0, z = 0.0 }

function Quaternion:new(newX --[[number]], newY --[[number]], newZ --[[number]], newW --[[number]])
    if type(newX) ~= "number"
            or type(newY) ~= "number"
            or type(newZ) ~= "number"
            or type(newW) ~= "number"
    then
        error("Can not create Quaternion")
    end

    qrt = {}
    self.__index = self
    setmetatable(qrt, self)

    qrt.x = newX
    qrt.y = newY
    qrt.z = newZ
    qrt.w = newW

    return qrt
end

function Quaternion:Set(newX --[[number]], newY --[[number]], newZ --[[number]], newW --[[number]])
    if type(newX) ~= "number"
            or type(newY) ~= "number"
            or type(newZ) ~= "number"
            or type(newW) ~= "number"
    then
        error("Can not set Quaternion")
    end

    self.x = newX
    self.y = newY
    self.z = newZ
    self.w = newW
end
