---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 12/30/23 1:51 AM
---

Transform = {
    position = { x = 0, y = 0, z = 0 },
    rotation = { x = 0, y = 0, z = 0, w = 0 }
}

function Transform:Rotate(angleX, angleY, angleZ, center)
    center = center or Space.Self
    print('  Transform :: Rotate(' .. angleX .. ', ' .. angleY .. ', ' .. angleZ .. ', ' .. center .. ')')
end

return Transform
