---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 12/30/23 10:31 AM
---

Vector3 = { x = 0.0, y = 0.0, z = 0.0 }
Vector3.zero = { x = 0.0, y = 0.0, z = 0.0 }

Vector3.forward = { x = 0.0, y = 0.0, z = 1.0 }
Vector3.back = { x = 0.0, y = 0.0, z = -1.0 }
Vector3.up = { x = 0.0, y = 1.0, z = 0.0 }
Vector3.down = { x = 0.0, y = -1.0, z = 0.0 }
Vector3.right = { x = 1.0, y = 0.0, z = 0.0 }
Vector3.left = { x = -1.0, y = 0.0, z = 0.0 }
