---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/20/24 1:45 PM
---

require "Core/LuaBehaviour"
require "Core/KeyCode"
require "Core/Application"

ApplicationSystem = LuaBehaviour:new()

function ApplicationSystem:Start()
    -- TODO:
end

function ApplicationSystem:Update()
    if Input.GetKeyUp(KeyCode.Escape) then
        Debug.Log("Quit...")
        Application.Quit();
    end
end
