---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 12/29/23 2:44 PM
---

require "Core/LuaBehaviour"

DroneController = {}

function DroneController:new()
    instance = {}
    instance.__name = ''
    instance.gameObject = nil
    instance.transform = nil
    setmetatable(instance, self)
    self.__index = self
    return instance
end

function DroneController:Start()
    if self.motionSpeed == nil then
        Debug.LogWarning("motionSpeed should not be equals zero")
    end
end

function DroneController:Update()
    if Input.GetButtonDown("Fire1") then
        Debug.Log("Fire!!!")
    end

    local horMove = Input.GetAxis("Horizontal");
    if horMove ~= 0.0 then
        local move = Vector3:new(horMove, 0.0, 0.0)
        self.transform:Translate(move * self.motionSpeed * Time.deltaTime);
    end

    local verMove = Input.GetAxis("Vertical")
    if verMove ~= 0.0 then
        local move = Vector3:new(0.0, 0.0, verMove)
        self.transform:Translate(move * self.motionSpeed * Time.deltaTime);
    end
end
