---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 12/29/23 2:44 PM
---

require "Core/LuaBehaviour"
require "Core/Time"

SpinnerController = {}

function SpinnerController:new()
    instance = {}
    instance.__name = ''
    instance.gameObject = nil
    instance.transform = nil
    setmetatable(instance, self)
    self.__index = self
    return instance
end

function SpinnerController:Start()
    if self.rotationSpeed == nil then
        Debug.LogWarning("rotationSpeed should not be equals zero")
    end
end

function SpinnerController:Update()
    if self == nil then
        Debug.LogWarning("self is null")
        return
    end
    if self.transform == nil then
        Debug.LogWarning("self.transform is null")
        return
    end
    self.transform:Rotate(Vector3:new(
            0.0,
            0.0,
            self.rotationSpeed * Time.deltaTime
    ))
    --Debug.Log("Angle Y for " .. self.gameObject.name .. " is " .. self.transform.rotation.eulerAngles.z);
end
