---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 12/29/23 2:44 PM
---

require "Core/Time"

SpinnerController = {}

function SpinnerController:Start()
    if self.rotationSpeed == nil then
        Debug.LogWarning("rotationSpeed should not be equals zero")
    end
end

function SpinnerController:Update()
    self.transform:Rotate(Vector3:new(
            0.0,
            0.0,
            self.rotationSpeed * Time.deltaTime
    ))
end
