---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/11/24 12:58 AM
---

package.path = package.path .. ';/home/goforbroke/CLionProjects/AmorphousEngine/cmake-build-debug//?.lua;./projects/01-HelloWorld//?.lua'
print(package.path)

require 'Core'
require 'Component'

__all_game_objects[0] = GameObject:new(0, 'Application System')
__all_game_objects[0].transform.position:Set(0.000000, 0.000000, 0.000000)
__all_game_objects[0].transform.rotation:Set(0.000000, 0.000000, 0.000000, 1.000000)
__all_game_objects[0].transform.localScale:Set(0.000000, 0.000000, 0.000000)

__all_game_objects[1] = GameObject:new(1, 'Main Camera')
__all_game_objects[1].transform.position:Set(0.000000, 100.000000, -100.000000)
__all_game_objects[1].transform.rotation:Set(-0.382683, 0.000000, 0.000000, 0.923880)

__all_game_objects[2] = GameObject:new(2, 'Light 1')
__all_game_objects[2].transform.position:Set(0.000000, 500.000000, 0.000000)
__all_game_objects[2].transform.rotation:Set(0.000000, 0.000000, 0.000000, 1.000000)

__all_game_objects[3] = GameObject:new(3, 'Barrel center')
__all_game_objects[3].transform.position:Set(0.000000, 0.000000, 0.000000)
__all_game_objects[3].transform.rotation:Set(0.000000, 0.000000, 0.000000, 1.000000)
__all_game_objects[3].transform.localScale:Set(1.500000, 1.500000, 1.500000)

__all_game_objects[4] = GameObject:new(4, 'Barrel front')
__all_game_objects[4].transform.position:Set(0.000000, 0.000000, 50.000000)
__all_game_objects[4].transform.rotation:Set(0.000000, 0.000000, 0.000000, 1.000000)
__all_game_objects[4].transform.localScale:Set(1.500000, 1.500000, 1.500000)

__all_game_objects[5] = GameObject:new(5, 'Barrel back')
__all_game_objects[5].transform.position:Set(0.000000, 0.000000, -50.000000)
__all_game_objects[5].transform.rotation:Set(0.000000, 0.000000, 0.000000, 1.000000)
__all_game_objects[5].transform.localScale:Set(1.500000, 1.500000, 1.500000)

__all_game_objects[6] = GameObject:new(6, 'Barrel right')
__all_game_objects[6].transform.position:Set(50.000000, 0.000000, 0.000000)
__all_game_objects[6].transform.rotation:Set(0.000000, 0.000000, 0.000000, 1.000000)
__all_game_objects[6].transform.localScale:Set(1.500000, 1.500000, 1.500000)

__all_game_objects[7] = GameObject:new(7, 'Barrel left')
__all_game_objects[7].transform.position:Set(-50.000000, 0.000000, 0.000000)
__all_game_objects[7].transform.rotation:Set(0.000000, 0.000000, 0.000000, 1.000000)
__all_game_objects[7].transform.localScale:Set(1.500000, 1.500000, 1.500000)

__all_game_objects[8] = GameObject:new(8, 'Drone 1')
__all_game_objects[8].transform.position:Set(1.000000, 0.000000, 50.000000)
__all_game_objects[8].transform.rotation:Set(0.000000, 0.000000, 0.000000, 1.000000)
__all_game_objects[8].transform.localScale:Set(0.250000, 0.250000, 0.250000)

require 'Scripts/ApplicationSystem'

function ApplicationSystem:new()
    local instance = LuaBehaviour:new()
    setmetatable(instance, self)
    self.__index = self
    return instance
end

require 'Scripts/DroneController'

function DroneController:new()
    local instance = LuaBehaviour:new()
    setmetatable(instance, self)
    self.__index = self
    return instance
end

require 'Scripts/SpinnerController'

function SpinnerController:new()
    local instance = LuaBehaviour:new()
    setmetatable(instance, self)
    self.__index = self
    return instance
end

__all_components['0 :: Scripts/ApplicationSystem'] = ApplicationSystem:new()
__all_components['0 :: Scripts/ApplicationSystem'].__type_name = 'Scripts/ApplicationSystem'
__all_components['0 :: Scripts/ApplicationSystem'].gameObject = __all_game_objects[0]
__all_components['0 :: Scripts/ApplicationSystem'].transform = __all_game_objects[0].transform

__all_components['0 :: Scripts/ApplicationSystem'].enabled = true

__all_components['1 :: Component/Camera'] = Camera:new()
__all_components['1 :: Component/Camera'].__type_name = 'Component/Camera'
__all_components['1 :: Component/Camera'].gameObject = __all_game_objects[1]
__all_components['1 :: Component/Camera'].transform = __all_game_objects[1].transform

__all_components['1 :: Component/Camera'].backgroundColor = Color:new(0.000000, 0.250000, 1.000000, 1.000000)
__all_components['1 :: Component/Camera'].enabled = true
__all_components['1 :: Component/Camera'].farClipPlane = 1000.000000
__all_components['1 :: Component/Camera'].nearClipPlane = 0.100000

__all_components['2 :: Component/Light'] = Light:new()
__all_components['2 :: Component/Light'].__type_name = 'Component/Light'
__all_components['2 :: Component/Light'].gameObject = __all_game_objects[2]
__all_components['2 :: Component/Light'].transform = __all_game_objects[2].transform

__all_components['2 :: Component/Light'].color = Color:new(1.000000, 0.920000, 0.016000, 1.000000)
__all_components['2 :: Component/Light'].enabled = true
__all_components['2 :: Component/Light'].type = 'Spot'

__all_components['3 :: Component/MeshRender'] = MeshRender:new()
__all_components['3 :: Component/MeshRender'].__type_name = 'Component/MeshRender'
__all_components['3 :: Component/MeshRender'].gameObject = __all_game_objects[3]
__all_components['3 :: Component/MeshRender'].transform = __all_game_objects[3].transform

__all_components['3 :: Component/MeshRender'].enabled = true
__all_components['3 :: Component/MeshRender'].path = 'Barrel.mesh'

__all_components['3 :: Scripts/SpinnerController'] = SpinnerController:new()
__all_components['3 :: Scripts/SpinnerController'].__type_name = 'Scripts/SpinnerController'
__all_components['3 :: Scripts/SpinnerController'].gameObject = __all_game_objects[3]
__all_components['3 :: Scripts/SpinnerController'].transform = __all_game_objects[3].transform

__all_components['3 :: Scripts/SpinnerController'].enabled = true
__all_components['3 :: Scripts/SpinnerController'].rotationSpeed = 10.000000

__all_components['4 :: Component/MeshRender'] = MeshRender:new()
__all_components['4 :: Component/MeshRender'].__type_name = 'Component/MeshRender'
__all_components['4 :: Component/MeshRender'].gameObject = __all_game_objects[4]
__all_components['4 :: Component/MeshRender'].transform = __all_game_objects[4].transform

__all_components['4 :: Component/MeshRender'].enabled = true
__all_components['4 :: Component/MeshRender'].path = 'Barrel.mesh'

__all_components['4 :: Scripts/SpinnerController'] = SpinnerController:new()
__all_components['4 :: Scripts/SpinnerController'].__type_name = 'Scripts/SpinnerController'
__all_components['4 :: Scripts/SpinnerController'].gameObject = __all_game_objects[4]
__all_components['4 :: Scripts/SpinnerController'].transform = __all_game_objects[4].transform

__all_components['4 :: Scripts/SpinnerController'].enabled = true
__all_components['4 :: Scripts/SpinnerController'].rotationSpeed = 15.000000

__all_components['5 :: Component/MeshRender'] = MeshRender:new()
__all_components['5 :: Component/MeshRender'].__type_name = 'Component/MeshRender'
__all_components['5 :: Component/MeshRender'].gameObject = __all_game_objects[5]
__all_components['5 :: Component/MeshRender'].transform = __all_game_objects[5].transform

__all_components['5 :: Component/MeshRender'].enabled = true
__all_components['5 :: Component/MeshRender'].path = 'Barrel.mesh'

__all_components['5 :: Scripts/SpinnerController'] = SpinnerController:new()
__all_components['5 :: Scripts/SpinnerController'].__type_name = 'Scripts/SpinnerController'
__all_components['5 :: Scripts/SpinnerController'].gameObject = __all_game_objects[5]
__all_components['5 :: Scripts/SpinnerController'].transform = __all_game_objects[5].transform

__all_components['5 :: Scripts/SpinnerController'].enabled = true
__all_components['5 :: Scripts/SpinnerController'].rotationSpeed = 10.000000

__all_components['6 :: Component/MeshRender'] = MeshRender:new()
__all_components['6 :: Component/MeshRender'].__type_name = 'Component/MeshRender'
__all_components['6 :: Component/MeshRender'].gameObject = __all_game_objects[6]
__all_components['6 :: Component/MeshRender'].transform = __all_game_objects[6].transform

__all_components['6 :: Component/MeshRender'].enabled = true
__all_components['6 :: Component/MeshRender'].path = 'Barrel.mesh'

__all_components['6 :: Scripts/SpinnerController'] = SpinnerController:new()
__all_components['6 :: Scripts/SpinnerController'].__type_name = 'Scripts/SpinnerController'
__all_components['6 :: Scripts/SpinnerController'].gameObject = __all_game_objects[6]
__all_components['6 :: Scripts/SpinnerController'].transform = __all_game_objects[6].transform

__all_components['6 :: Scripts/SpinnerController'].enabled = true
__all_components['6 :: Scripts/SpinnerController'].rotationSpeed = 10.000000

__all_components['7 :: Component/MeshRender'] = MeshRender:new()
__all_components['7 :: Component/MeshRender'].__type_name = 'Component/MeshRender'
__all_components['7 :: Component/MeshRender'].gameObject = __all_game_objects[7]
__all_components['7 :: Component/MeshRender'].transform = __all_game_objects[7].transform

__all_components['7 :: Component/MeshRender'].enabled = true
__all_components['7 :: Component/MeshRender'].path = 'Barrel.mesh'

__all_components['7 :: Scripts/SpinnerController'] = SpinnerController:new()
__all_components['7 :: Scripts/SpinnerController'].__type_name = 'Scripts/SpinnerController'
__all_components['7 :: Scripts/SpinnerController'].gameObject = __all_game_objects[7]
__all_components['7 :: Scripts/SpinnerController'].transform = __all_game_objects[7].transform

__all_components['7 :: Scripts/SpinnerController'].enabled = true
__all_components['7 :: Scripts/SpinnerController'].rotationSpeed = 10.000000

__all_components['8 :: Component/MeshRender'] = MeshRender:new()
__all_components['8 :: Component/MeshRender'].__type_name = 'Component/MeshRender'
__all_components['8 :: Component/MeshRender'].gameObject = __all_game_objects[8]
__all_components['8 :: Component/MeshRender'].transform = __all_game_objects[8].transform

__all_components['8 :: Component/MeshRender'].enabled = true
__all_components['8 :: Component/MeshRender'].path = 'ogrehead.mesh'

__all_components['8 :: Scripts/DroneController'] = DroneController:new()
__all_components['8 :: Scripts/DroneController'].__type_name = 'Scripts/DroneController'
__all_components['8 :: Scripts/DroneController'].gameObject = __all_game_objects[8]
__all_components['8 :: Scripts/DroneController'].transform = __all_game_objects[8].transform

__all_components['8 :: Scripts/DroneController'].enabled = true
__all_components['8 :: Scripts/DroneController'].motionSpeed = 10.000000

for _, cmpInstance in pairs(__all_components) do
    cmpInstance:Start()
end

__before_update_frame();
__on_update_frame();
__after_update_frame();

print(type(__all_components['8 :: Scripts/DroneController']['Update']))
