---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 12/29/23 2:44 PM
---

require 'Core/LuaBehaviour'

DroneController = LuaBehaviour:new()

DroneController.motionSpeed = 0.0
DroneController.targetObj = Transform

function DroneController:Start()
    Debug.Log("DroneController :: Start");

    self.motionSpeed = 0.25
    self.targetObj = Transform

    Debug.LogWarning("TODO: need to specify 'targetObj'");
end

function DroneController:Update()
    Debug.Log("DroneController :: Update");

    self.transform:LookAt(self.targetObj);
    self.transform:Translate(Vector3.right * self.motionSpeed * Time.deltaTime);
end
