---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/1/24 3:22 PM
---

-- TODO: implement universal import-all
-- https://www.reddit.com/r/neovim/comments/reovwj/how_to_require_an_entire_directory_in_lua/

for _, file in ipairs(vim.fn.readdir(vim.fn.stdpath('config')..'/lua/plugins', [[v:val =~ '\.lua$']])) do
  require('plugins.'..file:gsub('%.lua$', ''))
end
