---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 12/29/23 9:44 PM
---

print('Hello from file')

function print_hello()
    print('Hello from function')
end