---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 12/29/23 2:44 PM
---

RotatesAroundY = {}

function RotatesAroundY:Start()
    Debug.Log("RotatesAroundY :: Start");

    self.transform = Transform;
    self.rotationSpeed = 1.0
    self.angleY = 0.0
end

function RotatesAroundY:Update()
    Debug.Log("RotatesAroundY :: Update");

    self.angleY = self.angleY + Time.deltaTime * self.rotationSpeed
    self.transform:Rotate(0.0, self.angleY, 0.0, Space.Self);
end

return RotatesAroundY
