---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/2/24 11:03 PM
---

require 'Core/LuaBehaviour'

CharacterController = {}

function CharacterController:new()
    instance = LuaBehaviour:new()
    instance.isGrounded = false
    instance.center = Vector3.zero
    instance.height = 1.8
    instance.radius = 0.5
    instance.velocity = 0.2

    setmetatable(instance, self)
    self.__index = self
    return instance
end

function CharacterController:Start()
    -- Debug.Log("Camera :: Start");
end

function CharacterController:Update()
    -- Debug.Log("Camera :: Update");
end
