---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/2/24 11:03 PM
---

require 'Core/LuaBehaviour'

CharacterController = LuaBehaviour:new()

CharacterController.isGrounded = false
CharacterController.center = Vector3.zero
CharacterController.height = 1.8
CharacterController.radius = 0.5
CharacterController.velocity = 0.2

function CharacterController:Start()
    -- Debug.Log("Camera :: Start");
end

function CharacterController:Update()
    -- Debug.Log("Camera :: Update");
end
