---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/25/24 10:12 AM
---

require "Component/Camera"
require "Component/CharacterController"
require "Component/Light"
