---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 1/2/24 11:03 PM
---

require 'Core/LuaBehaviour'
require 'Core/Color'

Light = LuaBehaviour:new()

Light.color = Color.yellow

function Light:Start()
    -- Debug.Log("Camera :: Start");
end

function Light:Update()
    -- Debug.Log("Camera :: Update");
end
