---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by goforbroke.
--- DateTime: 2/10/24 11:07 PM
---

require 'Core/LuaBehaviour'

MeshRender = {
    path = ""
}

function MeshRender:new()
    instance = LuaBehaviour:new()
    instance.path = ""

    setmetatable(instance, self)
    self.__index = self
    return instance
end

function MeshRender:Start()
    -- Debug.Log("MeshRender :: Start");
end

function MeshRender:Update()
    -- Debug.Log("MeshRender :: Update");
end
